# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.5, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pytorch 1.5.1+cpu if python 3.5 (not mac)
      if: ${{ matrix.python-version == '3.5' && matrix.os != 'macos-latest' }}
      run: |
        pip install torch==1.5.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - name: Install pytorch 1.6.0+cpu if python > 3.5 (not mac)
      if:  ${{ matrix.python-version != '3.5' && matrix.os != 'macos-latest' }}
      run: |
        pip install torch==1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - name: Install basic dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[tests] -f https://download.pytorch.org/whl/torch_stable.html
    - name: Install extra dependencies
      run: |
        pip install .[extra,onnx,sparkml]
        pip install pandas
    - name: Generate Documentation
      run: |
        make sphinx-site -C website/
    - name: Deploy to GitHub pages
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: website/public/python_api
